version: '3.1'

services:
  web:
    image: registry.cn-shenzhen.aliyuncs.com/lidongming/my/posts:b58d769
    ports:
      - 8000:8000
    environment:
      - NODE_ENV=production
      - HTTP_ENDPOINT=http://39.108.107.106:4000/graphql
      - BROWSER_HTTP_ENDPOINT=http://39.108.107.106:4000/graphql
      